include ../../common/data.mk

DATA_FILES = power_512x2 power_512x4 power_512x8 power_64x8 temp_512x2 temp_512x4 temp_512x8 temp_64x8

.PHONY: all
all: $(DATA_FILES)

.PHONY: clean
clean:
	rm -f $(DATA_FILES)
